# Fichier de travail du labo 02 / lab 02 working file: sert uniquement à fabriquer des images
# rapidement. La syntaxe du Dockerfile est expliquee au labo 04.
FROM docker.io/library/alpine
RUN echo "version 1" > /version.txt
